source("functions.r")
vetor =  c(8,6,3,9,12,7,2,0,11,1,5,4,23,14)
cat("Lista não ordenada : \n")
cat(vetor,"\n\n")
cat("Criando um Heap\n")
vetor = criar_heap(vetor)
cat(vetor,"\n\n")
cat("Inserindo elemento 10","\n")
elem =  10
vetor  = inserir(vetor, elem)
cat(vetor,"\n\n")
cat("Descendo chave 1 na posição 2","\n")
vetor = descer(vetor,8,2)
cat(vetor,"\n\n")
cat("Subindo elemento 12 na posição 7","\n")
vetor = subir(vetor, 7)
cat(vetor,"\n\n")
cat("Removendo o elemento de maior prioridade","\n")
vetor = remover(vetor)
cat(vetor,"\n\n")
cat("Usando Heapsort","\n")
vetor = heapsort(vetor)
cat(vetor,"\n\n")